Android: gallium_dri: add include to get "xmlpool/options.h"
target.c requires "xmlpool/options.h" generated header
or the following tricky Android building error may appear:

In file included from external/mesa/src/gallium/targets/dri/target.c:1:
In file included from external/mesa/src/gallium/auxiliary/target-helpers/drm_helper.h:185:
out/target/product/x86_64/gen/STATIC_LIBRARIES/libmesa_pipe_radeonsi_intermediates/radeonsi/si_driinfo.h:19:7: error: expected '}'
      DRI_CONF_RADEONSI_ENABLE_SISCHED("false")
      ^
external/mesa/src/gallium/auxiliary/target-helpers/drm_helper.h:182:55: note: to match this '{'
   static const struct drm_conf_ret xml_options_ret = {
                                                      ^
1 error generated.

Fixes: 0f8c5de869 ("radeonsi: prepare for driver-specific driconf options")

Cc: "17.3" <mesa-stable@lists.freedesktop.org>