android: relax building errors due to warnings
To avoid the following building errors:

external/mesa/src/amd/vulkan/radv_meta_blit.c:620:27: error: taking the absolute value of unsigned type 'unsigned int' has no effect [-Werror,
-Wabsolute-value]
                dest_box.extent.width = abs(dst_x1 - dst_x0);
                                        ^
external/mesa/src/amd/vulkan/radv_meta_blit.c:620:27: note: remove the call to 'abs' since unsigned values cannot be negative
                dest_box.extent.width = abs(dst_x1 - dst_x0);
                                        ^~~
external/mesa/src/amd/vulkan/radv_meta_blit.c:621:28: error: taking the absolute value of unsigned type 'unsigned int' has no effect [-Werror,
-Wabsolute-value]
                dest_box.extent.height = abs(dst_y1 - dst_y0);
                                         ^
external/mesa/src/amd/vulkan/radv_meta_blit.c:621:28: note: remove the call to 'abs' since unsigned values cannot be negative
                dest_box.extent.height = abs(dst_y1 - dst_y0);
                                         ^~~
2 errors generated.

external/mesa/src/amd/vulkan/radv_query.c:1459:7: error: implicit conversion from 'unsigned long' to 'uint32_t' (aka 'unsigned int') changes v
alue from 18446744073709551615 to 4294967295 [-Werror,-Wconstant-conversion]
                         ? TIMESTAMP_NOT_READY : 0;
                           ^~~~~~~~~~~~~~~~~~~
external/mesa/src/amd/vulkan/radv_query.c:38:29: note: expanded from macro 'TIMESTAMP_NOT_READY'
                            ^~~~~~~~~~
bionic/libc/include/stdint.h:193:27: note: expanded from macro 'UINT64_MAX'
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
bionic/libc/include/stdint.h:142:27: note: expanded from macro 'UINT64_C'
                          ^~~~~~~
<scratch space>:74:1: note: expanded from here
18446744073709551615UL
^~~~~~~~~~~~~~~~~~~~~~
3 errors generated.

external/mesa/src/amd/vulkan/radv_pipeline.c:2810:8: error: 'const' type qualifier on return type has no effect [-Werror,-Wignored-qualifiers]
static const VkConservativeRasterizationModeEXT
       ^~~~~~
1 error generated.