android: gallium/auxiliary: fix microsoft tessellator build
Fixes the following building errors:

external/mesa/src/gallium/auxiliary/tessellator/tessellator.cpp:78:7: error: redefinition of 'fmin'
float fmin( float a, float b )
      ^
...
external/mesa/src/gallium/auxiliary/tessellator/tessellator.cpp:98:7: error: redefinition of 'fmax'
float fmax( float a, float b )
      ^
2 errors generated.

and the following Android Build System error:

FAILED:
build/make/core/binary.mk:1245: error: external/mesa/src/gallium/auxiliary/Android.mk: libmesa_gallium: Unused source files: tessellator/tessellator.hpp
10:24:30 ckati failed with: exit status 1

Fixes: bd0188f9 ("gallium/auxiliary: add the microsoft tessellator and a pipe wrapper.")
Signed-off-by: Mauro Rossi <issor.oruam@gmail.com>