HACK: nouveau/nil: remove idep_mesautil dependency to avoid c++/rust build error
Change requried due to e05415a8 "format: Generate endian-independent format aliases"

To avoid the following building error:

ERROR: Could not detect either libc++ or libstdc++ as your C++ stdlib implementation.