svga: fix git_sha1.h include path in Android.mk (v2)
Adds libmesa_git_sha1 static (dummy) library to generate git_sha1.h
Fixes the following building error:

external/mesa/src/gallium/drivers/svga/svga_screen.c:26:10:
fatal error: 'git_sha1.h' file not found
         ^
1 error generated.

Fixes: 1ce3a2723f9 ("svga: Add the ability to log messages to
vmware.log on the host.")