r600/sfn: include <array> where needed (v2)
Fixes the following building errors in Android:

In file included from external/mesa/src/gallium/drivers/r600/sfn/sfn_emitinstruction.cpp:27:
In file included from external/mesa/src/gallium/drivers/r600/sfn/sfn_emitinstruction.h:32:
In file included from external/mesa/src/gallium/drivers/r600/sfn/sfn_instruction_alu.h:30:
In file included from external/mesa/src/gallium/drivers/r600/sfn/sfn_instruction_base.h:30:
external/mesa/src/gallium/drivers/r600/sfn/sfn_value_gpr.h:107:11: error: implicit instantiation of undefined template 'std::__1::array<std::__1::shared_ptr<r600::Value>, 4>'
   Values m_elms;
          ^
external/libcxx/include/__tuple:223:64: note: template is declared here
template <class _Tp, size_t _Size> struct _LIBCPP_TEMPLATE_VIS array;
                                                               ^

(v2) include <array> only in sfn_value_gpr.h

Fixes: f718ac62 ("r600/sfn: Add a basic nir shader backend")
Signed-off-by: maurossi's avatarMauro Rossi <issor.oruam@gmail.com>