i965: fix glsl/float64_glsl.h include
Fixes the following build error:

external/mesa/src/mesa/drivers/dri/i965/brw_program.c:45:10:
fatal error: 'compiler/glsl/float64_glsl.h' file not found
#include "compiler/glsl/float64_glsl.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

Include of src/compiler in builddir is added accordingly

Signed-off-by: Mauro Rossi <issor.oruam@gmail.com>