android: freedreno/drm: add src/freedreno/common to include paths
Fixes the following building error:

In file included from external/mesa/src/freedreno/drm/freedreno_bo.c:30:
In file included from external/mesa/src/freedreno/drm/freedreno_priv.h:50:
external/mesa/src/freedreno/drm/freedreno_ringbuffer.h:38:10: fatal error: 'freedreno_pm4.h' file not found
         ^~~~~~~~~~~~~~~~~
1 error generated.

Fixes: 62c53d4361e ("freedreno/tu+drm: Extract out pm4 pkt header helpers")