android: radv/ac: Fix nir.h include
Fixes following building errors due to missing include paths:

external/mesa/src/amd/common/ac_shader_info.c:23:10: fatal error: 'nir/nir.h' file not found
#include "nir/nir.h"
         ^

external/mesa/src/compiler/nir/nir.h:48:10: fatal error: 'nir_opcodes.h' file not found
#include "nir_opcodes.h"
         ^

Fixes: 224cf29 "radv/ac: add initial pre-pass for shader info gathering"