android: util/format: fix build u_format_table.c gen rules
format/u_format_table.c generated source requires build rules
not ovelapping with existing generated sources build rules.

Fixes the following building error happening with Android Q:

FAILED:
external/mesa/src/util/Android.mk:115:
error: overriding commands for target `out/target/product/x86/gen/STATIC_LIBRARIES/libmesa_util_intermediates/format/u_format_table.c',
previously defined at external/mesa/src/util/Android.mk:74
15:49:47 ckati failed with: exit status 1

Fixes: 882ca6d ("util: Move gallium's PIPE_FORMAT utils to /util/format/")

Signed-off-by: Mauro Rossi <issor.oruam@gmail.com>