HACK: compiler/rust: remove idep_mesautil dependency to avoid c++/rust build error
Change required due to commit b60694b9 "compiler/rust: Add a float16 wrapper"

To avoid the following building error:

ERROR: Could not detect either libc++ or libstdc++ as your C++ stdlib implementation.