android: Remove util/debug.c source
minigbm generic dri depends on libmesa_loader static library
and libmesa_loader depends on libmesa_util static library

This change is due to commit
aa4ac5f ("utils: Merge util/debug.* into util/u_debug.* and remove util/debug.*")

Fixes the following building error:

error: external/mesa/src/util/Android.bp:23:1: module "libmesa_util" variant "android_x86_64_core_static":
module source path external/mesa/src/util/debug.c does not exist