nvk: Produce intrinsics in lower_{phis,ssa_defs}_to_regs
Change due to commits:

36b29201f "nir: Produce intrinsics in lower_{phis,ssa_defs}_to_regs"
e96a9a1b7 "nir: Remove nir_lower_regs_to_ssa"

Fixes the following building error:

FAILED: src/nouveau/vulkan/libvulkan_nouveau.so.p/nvk_shader.c.o
...
../src/nouveau/vulkan/nvk_shader.c:150:10: error: implicit declaration of function 'nir_lower_regs_to_ssa_impl' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
         nir_lower_regs_to_ssa_impl(function->impl);
         ^

1 error generated.