nvk: Remove all usage of nir_builder_init with nir_builder_create
Change due to commits:

48a25ef70 "treewide: Remove all usage of nir_builder_init with nir_builder_create and nir_builder_at"
97014036a "nir: Remove nir_builder_init, it's not used anymore"

Fixes the following building error:

FAILED: src/nouveau/vulkan/libvulkan_nouveau.so.p/nvk_shader.c.o
...
../src/nouveau/vulkan/nvk_shader.c:143:7: error: implicit declaration of function 'nir_builder_init' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
      nir_builder_init(&b, function->impl);
      ^

1 error generated.