android: iris: add missing backslash in Makefile.sources
Add the missing backslash in Makefile.sources

Fixes the following build error in Android:

[ 35% 137/391] including external/mesa/Android.mk ...
FAILED:
external/mesa/src/gallium/drivers/iris/Makefile.sources:46:
error: commands commence before first target.

Signed-off-by: Mauro Rossi <issor.oruam@gmail.com>
Fixes: 03432912 ("iris: Rename iris_seqno to iris_fine_fence")