Android.bp: loader: fix build after commit f839b95
Fixes the following building errors:

external/mesa/src/loader/loader.c:438:14: error: implicit declaration of function 'major' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
   int maj = major(sbuf.st_rdev);
             ^
external/mesa/src/loader/loader.c:439:14: error: implicit declaration of function 'minor' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
   int min = minor(sbuf.st_rdev);
             ^
2 errors generated.

ld.lld: error: undefined symbol: os_read_file
>>> referenced by loader.c:417 (external/mesa/src/loader/loader.c:417)