radeonsi: bugfix in performance counters
'if (regs->counters)' expression generates a warning,
which becomes an error with Android Build System,
counters[idx] is used to fix the condition checked.

Fixes the following building error in Android:

external/mesa/src/gallium/drivers/radeonsi/si_perfcounter.c:617:14:
error: address of array 'regs->counters' will always evaluate to 'true' [-Werror,-Wpointer-bool-conversion]
                        if (regs->counters)
                        ~~  ~~~~~~^~~~~~~~

Fixes: ad22006 "radeonsi: implement AMD_performance_monitor for CIK+"