android: radv: remove remaining KHR suffix
Fixes the following building error:

external/mesa/src/amd/vulkan/radv_android.c:233:11: error: implicit declaration of function 'radv_GetPhysicalDeviceImageFormatProperties2KHR' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        result = radv_GetPhysicalDeviceImageFormatProperties2KHR(phys_dev_h,
                 ^
1 error generated.

Fixes: bd1279bd9f ("Get rid of a bunch of KHR suffixes")