DO NOT MERGE: amd/common: ugly way to build w/o llvm 3.9 (v5)
HACK to workaround the drop of support of llvm 3.8 and llvm 3.9

(v1) Build with 12beef0 ("radeonsi: drop support for LLVM 3.8")
...
(v4) Build with 3bf1e03 ("amd: remove support for LLVM 3.9")
(v5) b2653007b9 ("ac/nir: move all RADV related code to radv_nir_to_llvm.c")

ATTENTION: randeonsi will not work with llvm 3.8 with these changes.
This is just to avoid following errors and test mesa-dev source build.

external/mesa/src/amd/common/ac_nir_to_llvm.c:3661:10:
error: incompatible integer to pointer conversion assigning to 'LLVMValueRef'
(aka 'struct LLVMOpaqueValue *') from 'int' [-Werror,-Wint-conversion]
                result = LLVMBuildAtomicCmpXchg(ctx->builder,
                       ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

external/mesa/src/amd/common/ac_nir_to_llvm.c:6242:20:
error: incompatible integer to pointer conversion initializing 'LLVMTargetDataRef'
(aka 'struct LLVMOpaqueTargetData *') with an expression of type 'int' [-Werror,-Wint-conversion]
        LLVMTargetDataRef data_layout = LLVMCreateTargetDataLayout(tm);
                          ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~