android: gallium/util: fix u_debug_stack_android build
Fix for build errors in src/gallium/auxiliary/util/u_debug_stack_android.cpp
error: cast to 'void *' from smaller integer type pid_t

Fixes: ff904978a1 ("gallium/util: Android backtrace support")