android: gallium/freedreno: Include libsync.h deps through libmesa_util
libmesa_util provides libsync.h as well as the right include directory
for the transitive dependency on android/sync.h:

    In file included from external/mesa3d/src/gallium/drivers/freedreno/a5xx/fd5_emit.c:34:
    In file included from external/mesa3d/src/gallium/drivers/freedreno/freedreno_resource.h:35:
    In file included from external/mesa3d/src/gallium/drivers/freedreno/freedreno_batch.h:328:
    In file included from external/mesa3d/src/gallium/drivers/freedreno/freedreno_context.h:33:
    external/mesa3d/src/util/libsync.h:48:10: fatal error: 'android/sync.h' file not found
    #include <android/sync.h>
             ^~~~~~~~~~~~~~~~

Fixes: e3c330c7b21 ("freedreno: Use Android's libsync instead of libdrm's.")
Acked-by: Eric Anholt <eric@anholt.net>