radeon: fix asserts in radeon_set_{context_reg_idx,uconfig_reg_idx}
Fixes the following building errors, caused by commit f41f78c
"radeonsi: drop the DRAW_PREAMBLE packet on Polaris" :

external/mesa/src/gallium/drivers/radeon/r600_cs.h: In function 'void radeon_set_context_reg_idx(radeon_winsys_cs*, unsigned int, unsigned int, unsigned int)':
external/mesa/src/gallium/drivers/radeon/r600_cs.h:105:13: error: 'struct radeon_winsys_cs' has no member named 'current'
  assert(cs->current.cdw + 3 <= cs->current.max_dw);
             ^
external/mesa/src/gallium/drivers/radeon/r600_cs.h:105:36: error: 'struct radeon_winsys_cs' has no member named 'current'
  assert(cs->current.cdw + 3 <= cs->current.max_dw);
                                    ^

external/mesa/src/gallium/drivers/radeon/r600_cs.h: In function 'void radeon_set_uconfig_reg_idx(radeon_winsys_cs*, unsigned int, unsigned int, unsigned int)':

external/mesa/src/gallium/drivers/radeon/r600_cs.h:144:13: error: 'struct radeon_winsys_cs' has no member named 'current'
  assert(cs->current.cdw + 3 <= cs->current.max_dw);
             ^
external/mesa/src/gallium/drivers/radeon/r600_cs.h:144:36: error: 'struct radeon_winsys_cs' has no member named 'current'
  assert(cs->current.cdw + 3 <= cs->current.max_dw);
                                    ^