genxml: Add gen10 alias for MOCS
Similar to

commit d9b4a81672ac46177bfc4f7515e8f5dc6ba6aff4
Author: Rafael Antognolli <rafael.antognolli@intel.com>
Date:   Tue May 9 17:12:09 2017 -0700

    genxml: Add alias for MOCS.

but for gen 10. Fixes the following compilation error:

genX_state_upload.c: In function 'gen10_emit_index_buffer':
genX_state_upload.c:861:9: error: 'struct GEN10_3DSTATE_INDEX_BUFFER' has no member named 'IndexBufferMOCS'
       ib.IndexBufferMOCS = GEN_GEN >= 9 ? SKL_MOCS_WB : BDW_MOCS_WB;

Signed-off-by: Ander Conselvan de Oliveira <ander.conselvan.de.oliveira@intel.com>