util/u_queue: use clock_gettime() instead of timespec_get()
clock_gettime(CLOCK_REALTIME, &ts) is equivalent to timespec_get(&ts, TIME_UTC)
but has the advantage that avoids the following building error when building with Android:

external/mesa/src/util/u_queue.c:173: error: undefined reference to 'timespec_get'

Fixes: e3a8013de8 ("util/u_queue: add util_queue_fence_wait_timeout")