egl: fold Android logger into main/ (swrast fix) (v2)
Fixes the folloing building error:

external/mesa/src/egl/drivers/dri2/platform_android.c:1492:19:
error: use of undeclared identifier 'droid_log'
   _eglSetLogProc(droid_log);
                  ^
1 error generated.

(v2) renamed dpy to disp after commit aa187fe7bfac856207a5feee36e17120a6ee9d22
"egl/android: Fix build break with dri2_initialize_android _EGLDisplay parameter"