egl/android: fix gralloc0 fallback paths (mesa 19.3)
Attempt to fix fallback to existing gralloc0 implementations,
to keep support for gbm_gralloc and drm_gralloc
Experimental build with HAVE_DRM_GRALLOC version of droid_open_device()

Changelog:
- Define GRALLOC_MODULE_PERFORM_GET_DRM_FD for gralloc0 fallback paths
- Use GRALLOC_MODULE_PERFORM_GET_DRM_FD in gralloc0->perform() calls
- Add HAVE_GRALLOC1 nested path in HAVE_DRM_GRALLOC version of droid_open_device()

NOTE: Since in gralloc 1.0 gralloc struct pointer is const hw_module_t *
the nested HAVE_GRALLOC1 paths inside HAVE_DRM_GRALLOC version of droid_open_device()
need to declare gralloc0 pointer as cast dri2_dpy->gralloc to type (const struct gralloc_module_t *)
in order to be able to access members like gralloc0->perform or gralloc0->common.name
which are missing gralloc 1.0 implementations.

Fixes the following build errors:

external/mesa/src/egl/drivers/dri2/platform_android.c:228:10: error: use of undeclared identifier 'GRALLOC_DRM_GET_FORMAT'
         GRALLOC_DRM_GET_FORMAT, buf->handle, &format);
         ^
external/mesa/src/egl/drivers/dri2/platform_android.c:1342:27: error: no member named 'perform' in 'struct hw_module_t'
   if (dri2_dpy->gralloc->perform)
       ~~~~~~~~~~~~~~~~~  ^
external/mesa/src/egl/drivers/dri2/platform_android.c:1343:35: error: no member named 'perform' in 'struct hw_module_t'
         err = dri2_dpy->gralloc->perform(dri2_dpy->gralloc,
               ~~~~~~~~~~~~~~~~~  ^
3 errors generated.