android: libmesa_glsl: add support for GLSL_TO_NIR_FILES
glsl_to_nir.cpp source was moved to GLSL_TO_NIR_FILES

src/glsl/Android.mk needs changes to take into account this,
to avoid the following building error in i965:

src/mesa/drivers/dri/i965/brw_nir.c:593: error: undefined reference to 'glsl_to_nir'
collect2: error: ld returned 1 exit status