Android: i965: add include to get "xmlpool/options.h"
intel_screen.c requires "xmlpool/options.h" generated header
or the following tricky Android building error may appear:

external/mesa/src/mesa/drivers/dri/i965/intel_screen.c:84:7: error: expected '}'
      DRI_CONF_ALLOW_GLSL_CROSS_STAGE_INTERPOLATION_MISMATCH("false")
      ^
external/mesa/src/mesa/drivers/dri/i965/intel_screen.c:46:63: note: to match this '{'
static const __DRIconfigOptionsExtension brw_config_options = {
                                                              ^
1 error generated.