android: always define __STDC_CONSTANT_MACROS
Android porting of commit 647d8e9
"configure.ac: always define __STDC_CONSTANT_MACROS"

Fixes the following building errors with kitkat-x86:

external/mesa/src/compiler/glsl/link_varyings.cpp: In member function 'unsigned int {anonymous}::varying_matches::assign_locations(gl_shader_program*, uint64_t, bool)':
external/mesa/src/compiler/glsl/link_varyings.cpp:1117:47: error: 'UINT64_C' was not declared in this scope
external/mesa/src/compiler/glsl/link_varyings.cpp: In function 'uint64_t reserved_varying_slot(gl_shader*, ir_variable_mode)':
external/mesa/src/compiler/glsl/link_varyings.cpp:1535:32: error: 'UINT64_C' was not declared in this scope