Revert "tgsi/ureg: always emit constants (and their decls) as 2D"
This reverts commit 41e342d54836f306c57c42c02c66a7e12201ec2f.

That commit causes webview can't display Youtube page in QEMU virgl.
The errors are shown in QEMU:

vrend_compile_shader: context error reported 10 "m.webview_shell" Illegal shader 0
shader failed to compile
0:17(22): error: `vsubo0contents' undeclared
0:17(22): error: type mismatch
0:17(21): error: type mismatch
0:17(15): error: cannot construct `vec2' from a non-numeric data type

GLSL:
in vec4 in_0;
in vec4 in_1;
uniform vec4 winsys_adjust;
vec4 temp0[2];
int addr0;
uniform uvec4 vsconst0[8];
void main(void)
{
temp0[0].x = float(intBitsToFloat(ivec4((in_1.xxxx))));
temp0[0].x = float(ivec4(floatBitsToInt(temp0[0].xxxx)));
temp0[0].x = float((max( temp0[0].xxxx , (vec4(0,0,0,0)))));
temp0[0].x = float((min( temp0[0].xxxx , (vec4(3,3,3,3)))));
temp0[0].x = float(intBitsToFloat(ivec4( temp0[0].xxxx )));
addr0 = int(floatBitsToInt(temp0[0].xxxx));
temp0[0].xy = vec2(((vsubo0contents[addr0 + 0].xyxx).xy));
temp0[1] = vec4(((uintBitsToFloat(vsconst0[4]) *  temp0[0].xxxx )));
temp0[0] = vec4((uintBitsToFloat(vsconst0[5]) *  temp0[0].yyyy  +  temp0[1] ));
temp0[0] = vec4((uintBitsToFloat(vsconst0[6]) * (in_0.zzzz) +  temp0[0] ));
temp0[0] = vec4((uintBitsToFloat(vsconst0[7]) * (in_0.wwww) +  temp0[0] ));
gl_Position = vec4(( temp0[0] ));
gl_Position.y = gl_Position.y * winsys_adjust.y;
gl_Position.z = dot(gl_Position, vec4(0.0, 0.0, winsys_adjust.zw));
}

vrend_report_buffer_error: context error reported 10 "m.webview_shell" Illegal command buffer 11011073