android: r600: build with -frtti cppflag
Fixes the following building error:

external/mesa/src/gallium/drivers/r600/sfn/sfn_instruction_export.cpp:132:24: error: cannot use dynamic_cast with -fno-rtti
   const auto& other = dynamic_cast<const WriteScratchInstruction&>(lhs);
                       ^
1 error generated.

Fixes: f718ac62688b ("r600/sfn: Add a basic nir shader backend")
Signed-off-by: Mauro Rossi <issor.oruam@gmail.com>