r600/sfn: remove try/catch in sfn_nir
To avoid following build error:

Fixes the following building error:

external/mesa/src/gallium/drivers/r600/sfn/sfn_nir.cpp:667:4: error: cannot use 'try' with exceptions disabled
   try {
   ^
1 error generated.

Fixes: f718ac62 ("r600/sfn: Add a basic nir shader backend")
Signed-off-by: maurossi's avatarMauro Rossi <issor.oruam@gmail.com>