android: fix libelf include path for Android 7.0
LOCAL_C_INCLUDES need to include correct path of libelf,
which had exceptions for Android 5.0 (i.e external/elfutils/0.153/libelf)
and Android 6.0 (i.e. external/elfutils/src/libelf)
In Android 7.0 the path is again external/elfutils/libelf

Fixes the following building error:

external/mesa/src/gallium/drivers/radeon/radeon_elf_util.c:32:10:
fatal error: 'gelf.h' file not found
#include <gelf.h>
         ^
1 error generated.