android: anv: remove remaining KHR suffix
Fixes the following building error:

external/mesa/src/intel/vulkan/anv_android.c:257:13: error: implicit declaration of function 'anv_GetPhysicalDeviceImageFormatProperties2KHR' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
   result = anv_GetPhysicalDeviceImageFormatProperties2KHR(phys_dev_h,
            ^
1 error generated.

Fixes: bd1279bd9f ("Get rid of a bunch of KHR suffixes")