DO NOT MERGE: radv: ugly way to build w/o llvm 3.9
HACK to workaround the drop of support of llvm 3.9 to build with
b2653007b9 ("ac/nir: move all RADV related code to radv_nir_to_llvm.c")

ATTENTION: radv will not work with llvm 3.8 with these changes.
This is just to avoid following error and test mesa-dev source build.

external/mesa/src/amd/vulkan/radv_nir_to_llvm.c:3015:20:
error: incompatible integer to pointer conversion initializing 'LLVMTargetDataRef'
(aka 'struct LLVMOpaqueTargetData *') with an expression of type 'int' [-Werror,-Wint-conversion]
        LLVMTargetDataRef data_layout = LLVMCreateTargetDataLayout(tm);
                          ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~