nvk/android: Avoid building error in nak bindings
Required to compile nvk for android

Fixes the following building error:

FAILED: src/nouveau/compiler/nak_bindings.rs
...
/usr/include/xf86drm.h:40:10: fatal error: 'drm.h' file not found
panicked at 'Unable to generate bindings: ClangDiagnostic("/usr/include/xf86drm.h:40:10:
fatal error: 'drm.h' file not found\n")', main.rs:52:36

Reviewed-by: Faith Ekstrand <faith.ekstrand@collabora.com>