intel/jay: fix build with older clang version
JAY_OPCODE_DESWIZZLE_ODD code path is wrapped with braces,
as done in JAY_OPCODE_CVT code path.

Fixes the following building errors happening with clang 11

../src/intel/compiler/jay/jay_to_binary.c:366:7: error: expected expression
      bool hi = simd_offs ? true : jay_deswizzle_odd_src2_hi(I);
      ^
../src/intel/compiler/jay/jay_to_binary.c:368:66: error: use of undeclared identifier 'hi'
              byte_offset(to_brw_reg(f, I, simd_offs, 0, false), hi ? 64 : 0));
                                                                 ^
2 errors generated.

Fixes: 6925d9ee ("jay: move deswizzle hack outside of swsb")