nvk: Support VK_KHR_shader_draw_parameters (v2)
We need to use nir_load_base_vertex() instead of nir_build_load_base_vertex()
due to commit ddb7cf7a ("nir/builder_opcodes: Remove nir_build_ prefixed helpers")

Fixes the following building errors:

FAILED: src/nouveau/vulkan/libvulkan_nouveau.so.p/nvk_shader.c.o
...
../src/nouveau/vulkan/nvk_shader.c:290:31: error: implicit declaration of function 'nir_build_load_base_vertex' is invalid in C99 [-Werror,-Wimplici
t-function-declaration]
   nir_ssa_def *base_vertex = nir_build_load_base_vertex(b);
                              ^
../src/nouveau/vulkan/nvk_shader.c:290:31: note: did you mean '_nir_build_load_base_vertex'?
src/compiler/nir/nir_builder_opcodes.h:6809:1: note: '_nir_build_load_base_vertex' declared here
_nir_build_load_base_vertex(nir_builder *build)
^
../src/nouveau/vulkan/nvk_shader.c:290:17: error: incompatible integer to pointer conversion initializing 'nir_ssa_def *' (aka 'struct nir_ssa_def *
') with an expression of type 'int' [-Werror,-Wint-conversion]
   nir_ssa_def *base_vertex = nir_build_load_base_vertex(b);
                ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/nouveau/vulkan/nvk_shader.c:909:56: warning: implicit conversion from 'int' to 'uint8_t' (aka 'unsigned char') changes value from 256 to 0 [-
Wconstant-conversion]
      shader->num_gprs = MIN2(info_out.bin.maxGPR + 5, 256); //XXX: why?
                       ~                               ^~~
../src/util/u_math.h:631:43: note: expanded from macro 'MIN2'
                                          ^
1 warning and 2 errors generated.