egl/android: remove swap_interval in swrast path
swap_interval in swrast path needs to be removed due to commit
23a09b4f67 "egl/dri2: Implement swapInterval fallback in a conformant way (v2)"

Fixes the following building error:

external/mesa/src/egl/drivers/dri2/platform_android.c:1493:22:
error: use of undeclared identifier 'dri2_fallback_swap_interval'
    .swap_interval = dri2_fallback_swap_interval,
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
                     dri2_setup_swap_interval