HACK: AOSP: allow missing unsafe on extern
To avoid the following building errors:

error: extern blocks should be unsafe
     --> src/compiler/rust/libcompiler.rlib.p/structured/bindings.rs:22108:1
      |
22108 |   extern "C" {
      |   ^
      |   |
      |  _help: needs `unsafe` before the extern keyword: `unsafe`
      | |
22109 | |     pub fn nir_gather_output_clipper_var_groups(
22110 | |         nir: *mut nir_shader,
22111 | |         groups: *mut nir_output_clipper_var_groups,
22112 | |     );
22113 | | }
      | |_^
      |
      = warning: this is accepted in the current edition (Rust 2021) but is a hard error in Rust 2024!
      = note: for more information, see <https://doc.rust-lang.org/nightly/edition-guide/rust-2024/unsafe-extern.html>

error: aborting due to 623 previous errors