android: radeonsi: fix building error in si_shader.c
Bionic does not support strchrnul() function,
causing the following building error:

external/mesa/src/gallium/drivers/radeonsi/si_shader.c:3863: error: undefined reference to 'strchrnul'
collect2: error: ld returned 1 exit status

This patch embeds the code of strchrnul() in si_shader.c,
in the same way described here:

http://lists.freedesktop.org/archives/piglit/2013-February/004798.html