android: util: Re-export headers from libsync
When building on Android the following error is observed:

    In file included from external/mesa3d/src/gallium/auxiliary/util/u_tests.c:513:
    external/mesa3d/src/util/libsync.h:48:10: fatal error: 'android/sync.h' file not found
    #include <android/sync.h>
             ^~~~~~~~~~~~~~~~

This include was recently added to libsync.h but not explicitly provided
by in-tree AOSP builds.

Fixes: 27b88879462 ("android: Add pre-4.7 Android kernel compatibility to our libsync header.")
Acked-by: Eric Anholt <eric@anholt.net>